id: project
title: Project Module
short_description: The structure of a guidedmodules.Project.
long_description: >
  This module provides the structure of a guidedmodules.Project.
introduction:
  format: markdown
  template: |
    Welcome to GovReady's Compliance Tool, Q.

    The purpose of Q is to collect the information you need to
    something something something something.

    *Directions:* Please complete each module in the tabs below.

questions:
  - id: q_project_name_id_managers
    title: Project Name, ID, and Managers
    type: module
    module-id: demo1_project_name_id_managers
    tab: Basic Info
    group: About the Project

  - id: q_project_need_capabilities
    title: Project Need and Capabiities
    type: module
    module-id: demo1_project_need_capabilities
    tab: Basic Info
    group: About the Project

  - id: q_project_user_types
    title: User Types
    type: module
    module-id: demo1_project_user_types
    tab: Basic Info
    group: Identity, Credential and Access Management

  - id: q_project_authentication_methods
    title: Authentication Methods
    type: module
    module-id: demo1_project_auth_methods
    tab: Basic Info
    group: Identity, Credential and Access Management

output:
  - tab: Basic Info
    format: markdown
    template: |
      Start by entering general information about this project.
