id: project
title: Project Module
short_description: The structure of a guidedmodules.Project.
long_description: >
  This module provides the structure of a guidedmodules.Project.
introduction:
  format: markdown
  template: |
    Welcome to GovReady's Compliance Tool, Q.

questions:
  - id: q99a
    title: Digital Identity 1
    type: module
    module-id: icam_example
    tab: Database
    group: Identity

  - id: q99b
    title: Digital Identity 2
    type: module
    module-id: icam_example
    tab: Web Server
    group: Identity

  - id: q99c
    title: Digital Identity 3
    type: module
    module-id: icam_example
    tab: Web Server
    group: SSL/TLS Certificate

  - id: q100a
    title: Select Animal 1
    type: module
    module-id: sample_module
    tab: Database
    group: Identity

  - id: q100b
    title: Select Animal 2
    type: module
    module-id: sample_module
    tab: Database
    group: IaaS Credentials

  - id: q100c
    title: Select Animal 3
    type: module
    module-id: sample_module
    tab: Web Server
    group: SSL/TLS Certificate

output:
  - name: Help
    format: markdown
    template: |
      Hi. Maybe we provide some help here.