id: project
title: Project Module
short_description: The structure of a guidedmodules.Project.
long_description: >
  This module provides the structure of a guidedmodules.Project.
introduction:
  format: markdown
  template: |
    Welcome to GovReady's Compliance Tool, Q.

questions:
  - id: q99a
    title: Purpose
    type: module
    module-id: icam_example
    tab: Basic Info
    group: About the Project

  - id: q99b
    title: Systems
    type: module
    module-id: icam_example
    tab: Basic Info
    group: About the Project

  - id: q99c
    title: Users
    type: module
    module-id: icam_example
    tab: Basic Info
    group: About the Project

  - id: q100a
    title: Select Animal 1
    type: module
    module-id: sample_module
    tab: Who's Who?
    group: Government Staff

  - id: q100b
    title: Select Animal 2
    type: module
    module-id: sample_module
    tab: Who's Who?
    group: Contractors

  - id: q100c
    title: Select Animal 3
    type: module
    module-id: sample_module
    tab: Who's Who?
    group: Vendors

output:
  - name: Help
    format: markdown
    template: |
      Hi. Maybe we provide some help here.