# Generated by Django 3.2.5 on 2022-01-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0065_elementcontrol_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.TextField(help_text='Description of the Element'),
        ),
        migrations.AlterField(
            model_name='elementcontrol',
            name='status',
            field=models.IntegerField(choices=[(2, 'Pending'), (3, 'Implemented'), (4, 'Assessed'), (5, 'Changes requested')], default=2),
        ),
    ]
