# A CircleCI configuration file because we do continuous integration testing!

version: 2

jobs:
  build:
    docker:
    - image: circleci/python:3.5-jessie-browsers # matches Python version in Ubuntu 16.04 in deployment, python:3.5-slim works but not with selenium

    steps:
    # Add .local/bin to PATH for utilities install by `pip install --user`.
    - run: echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV

    # Get source code.
    - checkout

    # Install dependencies.
    - run: sudo apt update && sudo apt install -y git curl unzip locales libmagic1 graphviz pandoc xvfb wkhtmltopdf
    - run: sudo sed -i "s/^[# ]*en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen && sudo /usr/sbin/locale-gen # Install the U.S. locale (see `apt install locales` above), which we reference explicitly in Q for formatting and parsing numbers. Usually only needed on slim builds of Debian images.
    - run: pip install --user -r requirements.txt
    - run: ./fetch-vendor-resources.sh

    # This is adapted from https://github.com/circleci/circleci-images/blob/master/shared/images/Dockerfile-browsers.template
    # but it still says chromium crashes when launched from selenium tests. Maybe because chromium
    # doesn't like to run as root --- need to try running it as non-root.
    ## Install selenium dependencies --- not needed if using circleci/python:3.5-jessie-browsers image.
    #- run: apt install chromedriver
    #- run: export DISPLAY=:99
    #- run: export CHROMIUM_FLAGS="--disable-setuid-sandbox --no-sandbox"
    #- run:
    #    name: Running X virtual framebuffer
    #    command: Xvfb :99 -screen 0 1280x1024x24
    #    background: true

    # Run tests.

    # Install packages necesary for requirements_txt_checker.sh,
    # and then run it.
    - run: pip3 install --user -U pip-tools safety
    - run: ./requirements_txt_checker.sh

    # Run static code analysis using 'bandit'.
    # Disable warning-like tests:
    # B101: Test for use of assert
    # B110: try_except_pass
    # B603: subprocess_without_shell_equals_true
    - run: bandit -s B101,B110,B603 -r discussion/ guidedmodules/ siteapp/

    # Run unit and functional tests with code coverage, and store code coverage
    # results. CircleCI commands can't go on forever, so we run the tests
    # separately (with -p) and then combine code coverage results.
    - run: coverage run --source='.' --branch -p manage.py test guidedmodules
    - run: coverage run --source='.' --branch -p manage.py test discussion
    - run: coverage run --source='.' --branch -p manage.py test siteapp.tests.LandingSiteFunctionalTests
    - run: coverage run --source='.' --branch -p manage.py test siteapp.tests.GeneralTests
    - run: coverage run --source='.' --branch -p manage.py test siteapp.tests.QuestionsTests
    - run: coverage combine
    - run: coverage report # output to studout.
    - run: coverage xml # generate report artifact coverage.xml.
    - run: coverage html # generate report artifact htmlcov/*.
    - store_artifacts:
        path: coverage.xml
    - store_artifacts:
        path: htmlcov
