id: app
title: About the Organization
type: system-project
hidden: true
version: 1
long_description: >
  This module is used for the main Project of each Organization.

introduction:
  format: markdown
  template: |
    Tell us about your organization.

questions:
  - id: organization_profile
    title: Organization Profile
    type: module
    module-id: organization_profile
    tab: Basic Info
    group: About the Organization

  - id: organization_details
    title: Organization Details
    type: module
    module-id: organization_classification
    tab: Basic Info
    group: About the Organization

  - id: point_of_contacts
    title: Points of Contact
    type: module-set
    module-id: point_of_contact
    tab: Basic Info
    group: Define Points of Contact

