id: app
title: New Compliance App
type: project
version: 0.1.0
icon: app.png
catalog:
  category: Draft
  vendor: GovReady
  vendor_url: ~
  status: stub
  version: 0.1.0
  source_url: ~
  description:
    short: |
      Short description.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: PM
introduction:
  format: markdown
  template: |
    Use this app to achieve compliance.
questions:
  - id: example
    title: Example Module
    type: module
    module-id: example
