# Generated by Django 3.2.5 on 2022-02-10 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0066_alter_elementcontrol_status'),
        ('project', '0002_package_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='catalog',
            field=models.OneToOneField(blank=True, help_text='Catalog of controls that the project uses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controls_catalog', to='controls.catalogdata'),
        ),
    ]
