# Generated by Django 3.2.5 on 2022-02-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_package_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='location',
            field=models.CharField(choices=[('cms_aws', 'CMS AWS Commercial'), ('govcloud', 'CMS AWS GovCloud'), ('azure', 'Microsoft Azure'), ('other', 'Other')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='impact_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('unknown', "Don't Know")], max_length=20),
        ),
    ]
