# Generated by Django 3.2.5 on 2022-02-10 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0066_alter_elementcontrol_status'),
        ('project', '0004_auto_20220210_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='component',
            field=models.ForeignKey(blank=True, help_text='Set of components that exist in the project', limit_choices_to={'element_type': 'system_element'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component', to='controls.element'),
        ),
        migrations.AlterField(
            model_name='package',
            name='impact_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('unknown', "Don't Know")], help_text='FISMA impact level of the project', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='location',
            field=models.CharField(choices=[('cms_aws', 'CMS AWS Commercial'), ('govcloud', 'CMS AWS GovCloud'), ('azure', 'Microsoft Azure'), ('other', 'Other')], default=None, help_text='Where the project is located', max_length=100),
        ),
    ]
