# Generated by Django 3.2.5 on 2022-02-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0066_alter_elementcontrol_status'),
        ('project', '0005_auto_20220210_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='package',
            name='component',
        ),
        migrations.RemoveField(
            model_name='package',
            name='creator',
        ),
        migrations.AddField(
            model_name='package',
            name='components',
            field=models.ManyToManyField(blank=True, help_text='Components that exist in the project', limit_choices_to={'element_type': 'system_element'}, null=True, related_name='used_by_projects', to='controls.Element'),
        ),
    ]
