# Generated by Django 3.2.5 on 2022-02-14 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controls', '0066_alter_elementcontrol_status'),
        ('project', '0006_auto_20220211_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='catalog',
            field=models.ForeignKey(blank=True, help_text='Catalog of controls that the project uses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_by_projects', to='controls.catalogdata'),
        ),
        migrations.AddField(
            model_name='package',
            name='creator',
            field=models.ForeignKey(default=None, help_text='User id of the project creator', on_delete=django.db.models.deletion.PROTECT, related_name='projects_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
