# Generated by Django 3.2.5 on 2022-02-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_package_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'permissions': [('can_add_members', 'Can add members'), ('can_delete_members', 'Can delete members')]},
        ),
    ]
