# Generated by Django 3.2.5 on 2022-02-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0066_alter_elementcontrol_status'),
        ('project', '0009_alter_package_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='components',
            field=models.ManyToManyField(blank=True, default=None, help_text='Components that exist in the project', limit_choices_to={'element_type': 'system_element'}, related_name='used_by_projects', to='controls.Element'),
        ),
    ]
