# Generated by Django 3.2.5 on 2022-02-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_package_impact_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
