# Generated by Django 3.2.5 on 2022-02-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_package_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='impact_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('unknown', "Don't Know")], default=None, help_text='FISMA impact level of the project', max_length=20, null=True),
        ),
    ]
