# Generated by Django 3.2.5 on 2022-03-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_package_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='acronym',
            field=models.CharField(default='TEST', help_text='Acronym for the name of the project', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(default='TEST', help_text='Name of the project', max_length=100),
            preserve_default=False,
        ),
    ]
