# Generated by Django 3.2.5 on 2022-04-15 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0017_auto_20220301_1825"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_project_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Is the user an administrator of the Project?",
                    ),
                ),
                (
                    "has_read_access",
                    models.BooleanField(
                        default=False, help_text="Can the user view the Project?"
                    ),
                ),
                (
                    "has_write_access",
                    models.BooleanField(
                        default=False, help_text="Can the user modify the Project?"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The Project this is defining membership for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="project.package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that is a member of the Project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "user")},
            },
        ),
    ]
