# Generated by Django 3.2.5 on 2022-04-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0019_auto_20220419_1504"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={
                "permissions": [
                    ("can_add_members", "Can add members"),
                    ("can_delete_members", "Can delete members"),
                ]
            },
        ),
    ]
