# Generated by Django 3.2.5 on 2022-04-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0021_alter_package_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={
                "permissions": [
                    ("can_add_members", "Can add members"),
                    ("can_delete_members", "Can delete members"),
                    ("dg_can_view_project", "OLP Can view project"),
                    ("package_permission_group", "Package Permission Group"),
                ]
            },
        ),
    ]
