# Generated by Django 3.2.5 on 2022-04-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0022_alter_package_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={
                "permissions": [
                    ("can_add_members", "Can add members"),
                    ("can_delete_members", "Can delete members"),
                    ("dg_can_view_project", "OLP Can view project"),
                    ("package_permission_group", "Package Permission Group"),
                    ("project_can_manage_users", "Can manage users on project"),
                    ("project_can_edit", "Can edit project"),
                    ("project_can_view", "Can view project"),
                ]
            },
        ),
    ]
