# Generated by Django 3.2.5 on 2022-04-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0023_alter_package_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={
                "permissions": [
                    ("project_can_manage_users", "Can manage users on project"),
                    ("project_can_edit", "Can edit project"),
                    ("project_can_view", "Can view project"),
                ]
            },
        ),
    ]
