# Generated by Django 3.2.5 on 2022-01-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0051_auto_20210822_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Full name to display.', max_length=200, null=True),
        ),
    ]
